from collections import OrderedDict

from .adaptive_recurrence import AdaptiveRecurrence

class FixedRecurrence:
    '''
    This recurrence class simply performs a fixed number of memory network steps and
    returns the memory representation and representation of the background knowledge
    generated by the knowledge_selector and knowledge_combiner layers (the simplest
    case being a weighted sum).
    '''
    def __init__(self, memory_network, num_memory_layers: int=3):

        self.num_memory_layers = num_memory_layers
        self.memory_network = memory_network

    def __call__(self, encoded_question, current_memory, encoded_background):
        for _ in range(self.num_memory_layers):
            current_memory, attended_knowledge = \
                self.memory_network.memory_step(encoded_question, current_memory, encoded_background)
        return current_memory, attended_knowledge

recurrence_modes = OrderedDict()  # pylint: disable=invalid-name
recurrence_modes["fixed"] = FixedRecurrence

recurrence_modes["adaptive"] = AdaptiveRecurrence
